package view;
import Model.Produto;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import DAO.ProdutoDAO;
import Model.Produto;

/**
 *
 * @author beatriz.silva19
 */
public class viewModel extends javax.swing.JPanel {

    /**
     * Creates new form viewModel
     */
    public viewModel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnFlag = new javax.swing.ButtonGroup();
        jPnlDadosProduto = new javax.swing.JPanel();
        lblNomeProduto = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblPrecoCompra = new javax.swing.JLabel();
        txtPrecoCompra = new javax.swing.JTextField();
        lblPrecoVenda = new javax.swing.JLabel();
        txtPrecoVenda = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        rdbtnHhabilitado = new javax.swing.JRadioButton();
        rdbtnDesabilitado = new javax.swing.JRadioButton();
        btnNovoProduto = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnSalvar = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnPesquisarProduto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnEditarProduto = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setBackground(new java.awt.Color(255, 255, 255));

        jPnlDadosProduto.setBackground(new java.awt.Color(255, 255, 255));

        lblNomeProduto.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblNomeProduto.setText("Produto:");

        txtNomeProduto.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        lblDescricao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblDescricao.setText("Descrição:");

        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        lblPrecoCompra.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblPrecoCompra.setText("Preço de Compra:");

        txtPrecoCompra.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        lblPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblPrecoVenda.setText("Preço de Venda:");

        txtPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtPrecoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoVendaActionPerformed(evt);
            }
        });

        lblQuantidade.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblQuantidade.setText("Quantidade:");

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        btnFlag.add(rdbtnHhabilitado);
        rdbtnHhabilitado.setText("Habilitado");
        rdbtnHhabilitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnHhabilitadoActionPerformed(evt);
            }
        });

        btnFlag.add(rdbtnDesabilitado);
        rdbtnDesabilitado.setText("Desabilitado");

        btnNovoProduto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnNovoProduto.setText("Novo");
        btnNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProdutoActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlDadosProdutoLayout = new javax.swing.GroupLayout(jPnlDadosProduto);
        jPnlDadosProduto.setLayout(jPnlDadosProdutoLayout);
        jPnlDadosProdutoLayout.setHorizontalGroup(
            jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDadosProdutoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlDadosProdutoLayout.createSequentialGroup()
                        .addGroup(jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao)
                            .addComponent(lblNomeProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlDadosProdutoLayout.createSequentialGroup()
                                .addComponent(btnNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNomeProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescricao)))
                    .addGroup(jPnlDadosProdutoLayout.createSequentialGroup()
                        .addComponent(lblPrecoCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblPrecoVenda)
                        .addGap(37, 37, 37)
                        .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPnlDadosProdutoLayout.createSequentialGroup()
                        .addComponent(lblQuantidade)
                        .addGroup(jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlDadosProdutoLayout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(rdbtnHhabilitado)
                                .addGap(18, 18, 18)
                                .addComponent(rdbtnDesabilitado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlDadosProdutoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(250, 250, 250)))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPnlDadosProdutoLayout.setVerticalGroup(
            jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlDadosProdutoLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoProduto)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeProduto)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPrecoCompra)
                        .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrecoVenda)))
                .addGroup(jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlDadosProdutoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlDadosProdutoLayout.createSequentialGroup()
                                .addComponent(rdbtnDesabilitado)
                                .addGap(60, 60, 60))
                            .addGroup(jPnlDadosProdutoLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPnlDadosProdutoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(rdbtnHhabilitado)
                        .addGap(18, 18, 18)
                        .addGroup(jPnlDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantidade)))))
        );

        btnExcluirProduto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnExcluirProduto.setText("Excluir");

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Produto", "Descrição", "Preço de Compra", "Preço de Venda", "Quantidade", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblProdutos);

        btnPesquisarProduto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnPesquisarProduto.setText("Pesquisar");
        btnPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdutoActionPerformed(evt);
            }
        });

        btnEditarProduto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnEditarProduto.setText("Editar");
        btnEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProdutoActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jPnlDadosProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPnlDadosProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisarProduto)
                    .addComponent(btnExcluirProduto)
                    .addComponent(btnEditarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutoActionPerformed
        // TODO add your handling code here:
        ButtonModel m = null;
        
        String produto = txtNomeProduto.getText();
        String descricao = txtDescricao.getText();
        String precoCompra = txtPrecoCompra.getText();
        String precoVenda = txtPrecoVenda.getText();
        String qtde = txtQuantidade.getText();
        boolean disponivel =btnFlag.isSelected(m);
        
        String categoria;
        
        Produto p = new Produto();
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnPesquisarProdutoActionPerformed

    private void btnNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProdutoActionPerformed
        // TODO add your handling code here:
        ButtonModel m = null;
        String produto = txtNomeProduto.getText();
        String descricao = txtDescricao.getText();
        String precoCompra = txtPrecoCompra.getText();
        String precoVenda = txtPrecoVenda.getText();
        String qtde = txtQuantidade.getText();
        boolean disponivel =btnFlag.isSelected(m);
        
        String categoria;
        
    }//GEN-LAST:event_btnNovoProdutoActionPerformed

    private void btnEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProdutoActionPerformed
        // TODO add your handling code here:ButtonModel m = null;
      
        ArrayList<Produto> listaProdutos = new ArrayList<>();
        
        //listaProdutos = ProdutoDAO.getProdutos(txtNomeProduto.getText());
                
        if (listaProdutos.size() > 0) {
            DefaultTableModel tmProdutos = (DefaultTableModel) this.tblProdutos.getModel();
            tmProdutos.setRowCount(0);
            
            for(Produto produto : listaProdutos) {
            
            String[] c = {String.valueOf(produto.getNome()),
                                         produto.getDescricao(),
                                         String.valueOf(produto.getPrecoCompra()),
                                         String.valueOf(produto.getPrecoVenda()),
                                         String.valueOf(produto.getQuantidade()),
                                          String.valueOf(produto.isDisponivel())};
            tmProdutos.addRow(c);
          }
        } else {
           JOptionPane.showMessageDialog(null, "Produto não encontrado");
        }

    }//GEN-LAST:event_btnEditarProdutoActionPerformed

    private void txtPrecoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoVendaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Produto p = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        
        p.setNome(txtNomeProduto.getText());
        p.setDescricao(txtDescricao.getText());
        p.setPrecoCompra(Float.parseFloat(txtPrecoCompra.getText()));
        p.setPrecoVenda(Float.parseFloat(txtPrecoVenda.getText()));
        p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        //Botão habilitado/desabilitado
        //p.setDisponivel(true);
        
        dao.inserir(p);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdbtnHhabilitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnHhabilitadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnHhabilitadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarProduto;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.ButtonGroup btnFlag;
    private javax.swing.JButton btnNovoProduto;
    private javax.swing.JButton btnPesquisarProduto;
    private javax.swing.JPanel jPnlDadosProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblPrecoCompra;
    private javax.swing.JLabel lblPrecoVenda;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JRadioButton rdbtnDesabilitado;
    private javax.swing.JRadioButton rdbtnHhabilitado;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPrecoCompra;
    private javax.swing.JTextField txtPrecoVenda;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
    public boolean validarFormulario(){
        ArrayList <String> erros = new ArrayList<String>();
        if(txtNomeProduto.getText().equals("")){
            erros.add("Defina um nome");
        }
        if(txtPrecoCompra.getText().equals("")){
            erros.add("Defina o preço de Compra");
        }
        if(txtPrecoVenda.getText().equals("")){
            erros.add("Defina preço de Venda");
        }
        if(txtQuantidade.getText().equals("")){
            erros.add("Defina a quantidade");
        }
        if(!rdbtnHhabilitado.isSelected() && !rdbtnDesabilitado.isSelected()){
            erros.add("Defina o status");
        }
        
        if (erros.size() > 0) {
            String resposta = "";

            for (String erro : erros) {
                resposta += erro + "\n";
            }

            JOptionPane.showMessageDialog(null, resposta, "Campos Inválidos", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
}
    private javax.swing.JButton btnSalvar;
    private javax.swing.JList<String> jList1;
